// Copyright 2019-Present LexLiu. All Rights Reserved.
#include "LexUIPostProcessVertexShader.usf"
#include "/Engine/Private/GammaCorrectionCommon.ush"
#include "/Engine/Generated/UniformBuffers/LexUIPostProcessMainTexUB.ush"

// reference from CompositeUIPixelShader.usf
float3 LinearizeColor(float3 EncodedColor)
{
#if MAC
		// Note, MacOSX native output is raw gamma 2.2 not sRGB!
		return pow(EncodedColor, 2.2);
#else
#if USE_709
			// Didn't profile yet if the branching version would be faster (different linear segment).
			return Rec709ToLinear(EncodedColor);
#else
    return sRGBToLinear(EncodedColor);
#endif
#endif
}

#if LEXUI_BLENDALPHA
half _BlendAlpha;
#endif

void SimpleCopyTargetPS(
    SimpleVSToPS input,
    out float4 OutColor : SV_Target0
)
{
    OutColor = LexUIPostProcessMainTexUB._MainTex.Sample(LexUIPostProcessMainTexUB._MainTexSampler, input.uv);
#if LEXUI_BLENDALPHA
    OutColor.a *= _BlendAlpha;
#endif
#if LEXUI_COLORCORRECT
    OutColor.rgb = LinearizeColor(OutColor.rgb);
#endif
}


float4 _MainTextureScaleOffset;
half _IsRenderTarget;//if this is render to TextureTarget or to Screen

void CopyMeshRegionPS(
    CopyMeshRegionVSToPS input,
    out float4 OutColor : SV_Target0
)
{
    float2 uv = input.uv;
    uv.xy = uv.xy * _MainTextureScaleOffset.xy + _MainTextureScaleOffset.zw;
    OutColor = LexUIPostProcessMainTexUB._MainTex.Sample(LexUIPostProcessMainTexUB._MainTexSampler, uv);
    //if render to screen then we need set alpha to 1, because default is 0 
    OutColor.a = _IsRenderTarget ? OutColor.a : 1;
#if LEXUI_COLORCORRECT
    OutColor.rgb = LinearizeColor(OutColor.rgb);
#endif
}