// Copyright 2019-Present LexLiu. All Rights Reserved.
#include "/Engine/Public/Platform.ush"

struct SimpleVSToPS
{
    float4 position : SV_Position;
    float2 uv : TEXCOORD0;
};

void SimplePostProcessVS(
    in float3 Position:ATTRIBUTE0,
    in float2 TextureCoord0 : ATTRIBUTE1,
    out SimpleVSToPS v2p
)
{
    v2p.position = float4(Position.xyz, 1.0);
    v2p.uv = TextureCoord0;
}


struct CopyMeshRegionVSToPS
{
    float4 position : SV_Position;
    float2 uv : TEXCOORD0;
};

void CopyMeshRegionVS(
    in float2 ScreenPosition : ATTRIBUTE0,
    in float2 TextureCoordinate : ATTRIBUTE1,
    out CopyMeshRegionVSToPS v2p
)
{
    v2p.position = float4(ScreenPosition.xy, 0.0, 1.0);
    v2p.uv = TextureCoordinate;
}