// Copyright 2019-Present LexLiu. All Rights Reserved.
#include "LexUIRenderMeshVertexShader.usf"
#include "/Engine/Generated/UniformBuffers/LexUIRenderMeshMainTexUB.ush"

#if LEXUI_CLIP
#include "../LexUIClip.ush"
#include "/Engine/Generated/UniformBuffers/LexUIRenderMeshClipDataTexUB.ush"
float4x4 _Inv_M;
#endif

#if LEXUI_BLEND_DEPTH
#include "/Engine/Generated/UniformBuffers/LexUIRenderMeshDepthTexUB.ush"
float4 _SceneDepthTextureScaleOffset;
float _SceneDepthBlend;
#if LEXUI_DEPTH_FADE
int _SceneDepthFade;
float2 _ViewSizeInv;
#endif
#endif

#if LEXUI_MASK
#include "/Engine/Generated/UniformBuffers/LexUIRenderMeshMaskTexUB.ush"
#endif

void RenderMeshPS(
    RenderMeshVSToPS input,
    out float4 OutColor : SV_Target0
)
{
    OutColor = LexUIRenderMeshMainTexUB._MainTex.Sample(LexUIRenderMeshMainTexUB._MainTexSampler, input.uv);
#if LEXUI_MASK
    OutColor.a *= LexUIRenderMeshMaskTexUB._MaskTex.Sample(LexUIRenderMeshMaskTexUB._MaskTexSampler, input.uv).r;
#endif
#if LEXUI_CLIP
	float3 localPosition = mul(float4(input.worldPosition, 1.0), _Inv_M).xyz;
	OutColor.a *= LexUI_CalculateClipData(LexUIRenderMeshClipDataTexUB._ClipDataTex, input.uv1.x, input.localPosition);
#endif
#if LEXUI_BLEND_DEPTH
    float PixelDepth = input.screenPosition.z / input.screenPosition.w;
	float2 ScreenUV = input.screenPosition.xy / input.screenPosition.w;
	ScreenUV = ScreenUV * 0.5f + float2(0.5f, 0.5f);
	ScreenUV.y = 1.0f - ScreenUV.y;
#if LEXUI_DEPTH_FADE
	float DepthFadeValue = 0;
	int SampleCount = 0;
	int SampleSize = _SceneDepthFade;
	ScreenUV = ScreenUV * _SceneDepthTextureScaleOffset.xy + _SceneDepthTextureScaleOffset.zw;
	for (int w = -SampleSize; w <= SampleSize; w++)
	{
		for (int h = -SampleSize; h <= SampleSize; h++)
		{
			float ExistDepth = LexUIRenderMeshDepthTexUB._SceneDepthTex.Sample(LexUIRenderMeshDepthTexUB._SceneDepthTexSampler, ScreenUV + float2(w, h) * _ViewSizeInv.xy).x;
			DepthFadeValue += step(ExistDepth, PixelDepth);
			SampleCount++;
		}
	}
	DepthFadeValue /= SampleCount;
	DepthFadeValue = smoothstep(0, 1, DepthFadeValue);
#else
    float ExistDepth = LexUIRenderMeshDepthTexUB._SceneDepthTex.Sample(LexUIRenderMeshDepthTexUB._SceneDepthTexSampler, ScreenUV * _SceneDepthTextureScaleOffset.xy + _SceneDepthTextureScaleOffset.zw).x;
	float DepthFadeValue = step(ExistDepth, PixelDepth);
#endif
	OutColor.a = lerp(_SceneDepthBlend * OutColor.a, OutColor.a, DepthFadeValue);
#endif
}

