// Copyright 2019-Present LexLiu. All Rights Reserved.
#include "LGUIPostProcessVertexShader.usf"
#include "/Engine/Public/Platform.ush"
#include "/Engine/Generated/UniformBuffers/LGUIPostProcessMainTexUB.ush"
#if USE_STRENGTH_TEXTURE
#include "/Engine/Generated/UniformBuffers/LGUIBlurStrengthTexUB.ush"
#endif

static float _Offset[3] =
{
    0.0,
	1.3846153846,
	3.2307692308
};

static float _Weight[3] =
{
    0.2270270270,
	0.3162162162,
	0.0702702703
};
float2 _BlurStrength;

float4 GaussianBlurPS(SimpleVSToPS input) : SV_Target0
{
#if USE_STRENGTH_TEXTURE
    float strength = LGUIBlurStrengthTexUB._StrengthTex.Sample(LGUIBlurStrengthTexUB._StrengthTexSampler, input.uv).r;
#endif
    float4 color = LGUIPostProcessMainTexUB._MainTex.Sample(LGUIPostProcessMainTexUB._MainTexSampler, input.uv) * _Weight[0];
    for (int i = 1; i < 3; i++)
    {
        float2 uvOffset = _Offset[i] * _BlurStrength;
#if USE_STRENGTH_TEXTURE
        uvOffset *= strength;
#endif
        color += LGUIPostProcessMainTexUB._MainTex.Sample(LGUIPostProcessMainTexUB._MainTexSampler, input.uv + uvOffset) * _Weight[i];
        color += LGUIPostProcessMainTexUB._MainTex.Sample(LGUIPostProcessMainTexUB._MainTexSampler, input.uv - uvOffset) * _Weight[i];
    }
    return color;
}
