// Copyright 2019-2021 LexLiu. All Rights Reserved.

#pragma once
#include "DetailLayoutBuilder.h"
#include "LGUIEditorModule.h"
#include "Engine/Selection.h"
#include "Editor.h"
#include "LGUIEditorTools.h"
#include "LGUIEditorUtils.h"
#include "IDetailChildrenBuilder.h"
#include "IDetailPropertyRow.h"
#include "IDetailGroup.h"
#include "IPropertyUtilities.h"
#include "EngineUtils.h"
#include "Framework/Application/SlateApplication.h"
#include "Framework/MultiBox/MultiBoxBuilder.h"
#include "EditorViewportClient.h"

#include "LGUIEditorStyle.h"
#include "LGUIEditorCommands.h"
#include "Thumbnail/LGUIPrefabThumbnailRenderer.h"
#include "Thumbnail/LGUISpriteThumbnailRenderer.h"
#include "Thumbnail/LGUISpriteDataBaseObjectThumbnailRenderer.h"
#include "ContentBrowserExtensions/LGUIContentBrowserExtensions.h"
#include "LevelEditorMenuExtensions/LGUILevelEditorExtensions.h"
#include "Window/LGUIAtlasViewer.h"

#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SCheckBox.h"
#include "Widgets/Input/STextComboBox.h"
#include "Widgets/Images/SImage.h"
#include "Widgets/Text/STextBlock.h"

#include "DataFactory/LGUISpriteDataTypeAction.h"
#include "DataFactory/LGUIFontDataTypeAction.h"

#include "DetailCustomization/UIItemCustomization.h"
#include "DetailCustomization/UISpriteBaseCustomization.h"
#include "DetailCustomization/UISpriteCustomization.h"
#include "DetailCustomization/UITextureCustomization.h"
#include "DetailCustomization/LGUICanvasCustomization.h"
#include "DetailCustomization/UITextCustomization.h"
#include "DetailCustomization/UITextureBaseCustomization.h"
#include "DetailCustomization/LGUISpriteDataCustomization.h"
#include "DetailCustomization/LGUIFontDataCustomization.h"
#include "DetailCustomization/UISelectableCustomization.h"
#include "DetailCustomization/UIToggleCustomization.h"
#include "DetailCustomization/UITextInputCustomization.h"
#include "DetailCustomization/UILayoutBaseCustomization.h"
#include "DetailCustomization/UIVerticalLayoutCustomization.h"
#include "DetailCustomization/UIHorizontalLayoutCustomization.h"
#include "DetailCustomization/UIGridLayoutCustomization.h"
#include "DetailCustomization/UILayoutElementCustomization.h"
#include "DetailCustomization/UICanvasScalerCustomization.h"
#include "DetailCustomization/LGUIPrefabHelperComponentCustomization.h"
#include "DetailCustomization/LGUIPrefabCustomization.h"
#include "DetailCustomization/LGUIDrawableEventOneParamCustomization.h"
#include "DetailCustomization/LGUIDrawableEventOnePresetParamCustomization.h"
#include "DetailCustomization/LGUIComponentRefereceCustomization.h"
#include "DetailCustomization/UIEffectTextAnimationCustomization.h"
#include "DetailCustomization/UIScrollViewWithScrollBarCustomization.h"
#include "DetailCustomization/UISpriteSequencePlayerCustomization.h"
#include "DetailCustomization/UISpriteSheetTexturePlayerCustomization.h"

#include "LGUIHeaders.h"
#include "Core/Actor/LGUIManagerActor.h"
