
void LexUI_ReadClipData(Texture2D DataTex, inout int3 Position, out float4x4 CanvasToClipMatrix, out float HalfWidth, out float HalfHeight, out float Softness, out float IsValid)
{
	float4 Column0 = DataTex.Load(Position);Position.x += 1;
	float4 Column1 = DataTex.Load(Position);Position.x += 1;
	float4 Column2 = DataTex.Load(Position);Position.x += 1;
	float4 Column3 = DataTex.Load(Position);Position.x += 1;
	HalfWidth = Column3.x;
	HalfHeight = Column3.y;
	Softness = Column3.z;
	IsValid = Column3.w;
	Column3 = float4(0, 0, 0, 1);
	CanvasToClipMatrix[0] = Column0;
	CanvasToClipMatrix[1] = Column1;
	CanvasToClipMatrix[2] = Column2;
	CanvasToClipMatrix[3] = Column3;
}
// reference from https://www.shadertoy.com/view/4tGGRm
float LexUIClip_sdRoundRect(float2 p, float2 b, float4 r)
{
	r.xyzw = min(r.xyzw, min(b.x, b.y));
	r.xy = (p.x > 0.0) ? r.xy : r.wz;
	r.x = (p.y > 0.0) ? r.x : r.y;
	float2 q = abs(p) - b + r.x;
	float d = min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r.x;
	return d;
}
#define LexUI_Clip_Depth 8
#define LexUI_Clip_Enable_Rounded 1
float LexUI_CalculateClipData(Texture2D DataTex, float CoordinateInDataTex, float3 PixelLocalPosition)
{
	int Coordinate = round(CoordinateInDataTex);
	if (Coordinate == 0) return 1.0f;//0 position means no clip
	float finalAlpha = 1.0f;
	int3 Position = int3(0, Coordinate, 0);
	for (int i = 0; i < LexUI_Clip_Depth; i++)
	{
		float4x4 CanvasToClipMatrix;
		float HalfWidth, HalfHeight;
		float Softness = 0;
		float IsValid = 1;
		LexUI_ReadClipData(DataTex, Position, CanvasToClipMatrix, HalfWidth, HalfHeight, Softness, IsValid);
		if (!IsValid)break;

		float3 PixelPosition = mul(CanvasToClipMatrix, float4(PixelLocalPosition.xyz, 1.0)).xyz;
#if LexUI_Clip_Enable_Rounded
		float4 CornerRadius = DataTex.Load(Position);Position.x += 1;
		float Alpha = LexUIClip_sdRoundRect(PixelPosition.yz, float2(HalfWidth, HalfHeight), CornerRadius);
		Alpha = Alpha / fwidth(Alpha);
		Alpha = saturate(0 - Alpha);
		finalAlpha *= Alpha;
#else
		float2 Alpha2 = abs(PixelPosition.yz) - float2(HalfWidth, HalfHeight);
		Alpha2 = saturate(Alpha2);
		float Alpha = 1.0 - saturate(Alpha2.x + Alpha2.y);
		finalAlpha *= Alpha;
#endif
	}
	return finalAlpha;
}